default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: de4ejsjhgrcuv5
  username: bxibezorjcipfz
  password: 6ad88522e69e19ab6b02bec3fbd80e37ea6193c23c02c1befab88984a810d75d
  host: ec2-54-146-4-66.compute-1.amazonaws.com

test:
  <<: *default
  database: de4ejsjhgrcuv5
  username: bxibezorjcipfz
  password: 6ad88522e69e19ab6b02bec3fbd80e37ea6193c23c02c1befab88984a810d75d
  host: ec2-54-146-4-66.compute-1.amazonaws.com

production:
  <<: *default
  database: de4ejsjhgrcuv5
  username: bxibezorjcipfz
  password: 6ad88522e69e19ab6b02bec3fbd80e37ea6193c23c02c1befab88984a810d75d
  host: ec2-54-146-4-66.compute-1.amazonaws.com
